package sk.musiccards.cards;

import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

import sk.musiccards.core.PlaylistExport;
import sk.musiccards.core.SpotifyLink;

/**
 * Merges Spotify playlist exports (Exportify CSV) into the card catalog
 * format (data/songs.csv). Deduplicates by track id and by normalized
 * title+artist, sorts by year, and prints data-quality warnings — most
 * importantly for years that come from compilation albums.
 *
 * Usage: ImportPlaylists <output.csv> <export1.csv> [export2.csv ...]
 */
public final class ImportPlaylists {

    public static void main(String[] args) throws IOException {
        if (args.length < 2) {
            System.err.println("usage: ImportPlaylists <output.csv> <export1.csv> [export2.csv ...]");
            System.exit(2);
        }

        Map<String, PlaylistExport.Entry> byTrackId = new HashMap<>();
        Set<String> byTitleArtist = new HashSet<>();
        List<PlaylistExport.Entry> songs = new ArrayList<>();
        int rows = 0, dupId = 0, dupTitle = 0, noYear = 0;

        for (int i = 1; i < args.length; i++) {
            List<PlaylistExport.Entry> entries;
            try (FileReader reader = new FileReader(args[i], StandardCharsets.UTF_8)) {
                entries = PlaylistExport.parse(reader);
            }
            System.out.println(args[i] + ": " + entries.size() + " tracks");
            for (PlaylistExport.Entry e : entries) {
                rows++;
                if (byTrackId.containsKey(e.trackId)) {
                    dupId++;
                    continue;
                }
                String key = normalize(e.title) + "|" + normalize(e.artist);
                if (byTitleArtist.contains(key)) {
                    dupTitle++;
                    System.out.println("  DUPLICATE (different track id, same song?): "
                            + e.artist + " - " + e.title);
                    continue;
                }
                if (e.year == 0) {
                    noYear++;
                    System.out.println("  SKIPPED (no release year): " + e.artist + " - " + e.title);
                    continue;
                }
                byTrackId.put(e.trackId, e);
                byTitleArtist.add(key);
                songs.add(e);
            }
        }

        songs.sort(Comparator
                .comparingInt((PlaylistExport.Entry e) -> e.year)
                .thenComparing(e -> e.artist, String.CASE_INSENSITIVE_ORDER)
                .thenComparing(e -> e.title, String.CASE_INSENSITIVE_ORDER));

        int suspicious = 0;
        try (PrintWriter out = new PrintWriter(
                Files.newBufferedWriter(Paths.get(args[0]), StandardCharsets.UTF_8))) {
            out.println("# Music Cards song catalog — one physical card per line.");
            out.println("# Format: title;artist;year;spotify-link");
            out.println("# Generated by ImportPlaylists (make import); edit years freely, they");
            out.println("# come from the ALBUM release date and compilations are marked below.");
            for (PlaylistExport.Entry e : songs) {
                if (e.suspiciousYear) {
                    suspicious++;
                    out.println("# CHECK YEAR (album \"" + e.album + "\" looks like a compilation):");
                }
                out.println(clean(e.title) + ";" + clean(e.artist) + ";" + e.year + ";"
                        + SpotifyLink.toUri(e.trackId));
            }
        }

        System.out.println();
        System.out.println("Read " + rows + " rows -> wrote " + songs.size() + " songs to " + args[0]);
        System.out.println("  skipped: " + dupId + " duplicate track ids, " + dupTitle
                + " same title+artist, " + noYear + " without a year");
        System.out.println("  " + suspicious + " songs marked '# CHECK YEAR' (compilation album "
                + "date, likely later than the original release) — review them before printing.");
    }

    /** Field separator is ';' and '#' starts a comment — keep them out of fields. */
    private static String clean(String s) {
        return s.replace(';', ',').replace('\n', ' ').replace("#", "").trim();
    }

    /** Lowercase, strip diacritics ("Tanečnice" == "Tanecnice") and punctuation. */
    private static String normalize(String s) {
        String folded = java.text.Normalizer.normalize(s, java.text.Normalizer.Form.NFD)
                .replaceAll("\\p{M}+", "");
        return folded.toLowerCase(Locale.ROOT).replaceAll("[^\\p{L}\\p{N}]+", " ").trim();
    }

    private ImportPlaylists() {
    }
}
